"""
Django settings for backend project.
Generated by 'django-admin startproject' using Django 6.0.2.
"""

from pathlib import Path
import os

# ================================
# BASE DIRECTORY
# ================================
BASE_DIR = Path(__file__).resolve().parent.parent

# ================================
# GDAL (GeoDjango)
# ================================
GDAL_LIBRARY_PATH = "/usr/lib/x86_64-linux-gnu/libgdal.so"

# ================================
# SECURITY
# ================================
SECRET_KEY = 'django-insecure--5nap*7!%8+ydky_a-%z&$5bbuuk6)5rdg@#u=-@vqc@i&5!zx'
DEBUG = True
ALLOWED_HOSTS = []

# ================================
# APPLICATIONS
# ================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Geo
    'django.contrib.gis',

    # Third party
    'rest_framework',
    'rest_framework_gis',
    'corsheaders',

    # Local app
    'api',
]

# ================================
# MIDDLEWARE
# ================================
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

# ================================
# ROOT URL
# ================================
ROOT_URLCONF = 'backend.urls'

# ================================
# TEMPLATES
# ================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# ================================
# DATABASE (POSTGIS)
# ================================
DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'webgis_ta',
        'USER': 'radja',
        'PASSWORD': 'Ratuadzkia17',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# ================================
# PASSWORD VALIDATION
# ================================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ================================
# INTERNATIONALIZATION
# ================================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Jakarta'
USE_I18N = True
USE_TZ = True

# ================================
# STATIC FILES
# ================================
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

# ================================
# AUTH REDIRECT SETTINGS
# ================================
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/map/'
LOGOUT_REDIRECT_URL = '/'

# ================================
# DJANGO REST FRAMEWORK
# ================================
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}

# ================================
# DEFAULT AUTO FIELD
# ================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'