# Generated by Django 5.2.11 on 2026-02-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='das',
            name='nama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
