# Generated by Django 5.2.11 on 2026-02-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_das_nama'),
    ]

    operations = [
        migrations.AddField(
            model_name='titik',
            name='kamar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='titik',
            name='kapasitas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
