# Generated by Django 6.0.2 on 2026-02-28 17:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_titik_kamar_titik_kapasitas'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatchmentArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('luas_ha', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FasilitasWisata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jenis', models.CharField(choices=[('hotel', 'Hotel'), ('resto', 'Restoran'), ('homestay', 'Homestay')], max_length=20)),
                ('lokasi', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('kamar', models.IntegerField(blank=True, null=True)),
                ('kapasitas', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JaringanPipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('diameter_mm', models.FloatField(blank=True, null=True)),
                ('kondisi', models.CharField(blank=True, max_length=50, null=True)),
                ('tahun_pasang', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permukiman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_dusun', models.CharField(max_length=100)),
                ('lokasi', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('jumlah_kk', models.IntegerField()),
                ('jumlah_penduduk', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RechargeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('kelas_potensi', models.CharField(blank=True, max_length=50, null=True)),
                ('luas_ha', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('lokasi', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('kapasitas_m3', models.FloatField()),
                ('elevasi', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SumberAir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('lokasi', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('debit', models.FloatField(help_text='L/detik')),
                ('jenis_sumber', models.CharField(blank=True, max_length=50, null=True)),
                ('kondisi', models.CharField(blank=True, max_length=50, null=True)),
                ('tahun_pendataan', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Titik',
        ),
    ]
