# Generated by Django 6.0.4 on 2026-04-17 04:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_catchmentarea_fasilitaswisata_jaringanpipa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrasiDesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namobj', models.CharField(blank=True, max_length=200, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('wadmkd', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nama Desa')),
                ('wadmkc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nama Kecamatan')),
                ('wadmkk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nama Kabupaten')),
                ('wadmpr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nama Provinsi')),
                ('luas', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'Administrasi Desa',
                'verbose_name_plural': 'Administrasi Desa',
            },
        ),
    ]
