# Generated by Django 6.0.4 on 2026-04-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_administrasidesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='fasilitaswisata',
            name='kebutuhan_air_harian',
            field=models.FloatField(blank=True, help_text='Liter/hari', null=True),
        ),
        migrations.AddField(
            model_name='permukiman',
            name='kategori_pelanggan',
            field=models.CharField(blank=True, choices=[('rumah_tangga', 'Rumah Tangga'), ('homestay', 'Homestay'), ('warung', 'Warung'), ('fasum', 'Fasilitas Umum')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='permukiman',
            name='rata_rata_kebutuhan',
            field=models.FloatField(blank=True, help_text='Liter/hari', null=True),
        ),
        migrations.AddField(
            model_name='sumberair',
            name='foto_dokumentasi',
            field=models.ImageField(blank=True, null=True, upload_to='foto_sumber_air/'),
        ),
        migrations.AlterField(
            model_name='fasilitaswisata',
            name='jenis',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('resto', 'Restoran'), ('homestay', 'Homestay'), ('jasa', 'Jasa')], max_length=20),
        ),
    ]
