# Generated by Django 6.0.4 on 2026-06-02 22:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sungai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=200)),
                ('tipe', models.CharField(blank=True, max_length=100)),
                ('kelas', models.CharField(blank=True, max_length=100)),
                ('das', models.CharField(blank=True, max_length=200)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Sungai',
            },
        ),
    ]
