# Generated by Django 6.0.4 on 2026-06-07 05:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_sungai'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sungai',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='pesan',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='tanggal',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
