# Generated by Django 6.0.4 on 2026-06-09 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_conversation_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catchmentarea',
            options={'verbose_name': 'Debit Puncak Aliran', 'verbose_name_plural': 'Debit Puncak Aliran'},
        ),
        migrations.AlterModelOptions(
            name='rechargearea',
            options={'verbose_name': 'Daerah Potensi Air Tanah', 'verbose_name_plural': 'Daerah Potensi Air Tanah'},
        ),
        migrations.AlterModelOptions(
            name='reservoir',
            options={'verbose_name': 'Tandon Air', 'verbose_name_plural': 'Tandon Air'},
        ),
    ]
